// Generated by the source analyzer from https://api.openbrewerydb.org
// 2026-06-12T21:07:53.532Z — do not edit by hand; re-add the URL from the dashboard to regenerate.
// Why api: Free, documented JSON API listing breweries worldwide; no auth required.
import { defineApiSource } from '../runtime/apiSource.js';

export default defineApiSource({
  "id": "custom_api_openbrewerydb_org",
  "label": "Open Brewery DB",
  "addedFrom": "https://api.openbrewerydb.org",
  "spec": {
    "baseUrl": "https://api.openbrewerydb.org/v1",
    "docsUrl": "https://www.openbrewerydb.org/documentation",
    "listPath": "/breweries",
    "queryParams": {
      "sort": "name:asc"
    },
    "pageParam": "page",
    "itemsPath": "",
    "fieldMap": {
      "brand": "name",
      "producer": "name",
      "beverageClass": "brewery_type",
      "origin": "country",
      "sourceRef": "id",
      "sourceUrl": "website_url"
    },
    "auth": {
      "type": "none"
    },
    "credentials": []
  }
});
