import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { registerSource } from './index.js';
import type { Source } from '../types.js';
import type { SourceAnalysis } from '../agent/sourceAnalyzer.js';

/**
 * User-added sources live as generated TypeScript files in src/sources/custom/.
 * Each file is a thin declarative wrapper over defineApiSource/defineAgenticSource
 * (the spec comes from the analyzer); credentials are NOT written into the file —
 * they live in data/credentials.json. Files are dynamically imported (tsx runs
 * the project, so importing .ts at runtime works) and registered on startup.
 */

const CUSTOM_DIR = join(dirname(fileURLToPath(import.meta.url)), 'custom');

/** Generate the connector file for an analysis, import it, and register it. */
export async function generateAndRegisterSource(analysis: SourceAnalysis): Promise<Source> {
  const slug = slugFor(analysis.url);
  const id = `custom_${slug}`;
  const file = join(CUSTOM_DIR, `${slug}.ts`);

  await mkdir(CUSTOM_DIR, { recursive: true });
  await writeFile(file, renderSourceFile(id, analysis));

  // Cache-bust so re-adding the same site picks up the regenerated file.
  const source = await importSourceFile(file, true);
  registerSource(source);
  return source;
}

/** Import + register every generated connector. Called once at startup. */
export async function loadCustomSources(): Promise<void> {
  let entries: string[];
  try {
    entries = await readdir(CUSTOM_DIR);
  } catch {
    return; // no custom sources yet
  }
  for (const name of entries) {
    if (!name.endsWith('.ts')) continue;
    try {
      registerSource(await importSourceFile(join(CUSTOM_DIR, name)));
    } catch (err) {
      console.error(`failed to load custom source ${name}: ${(err as Error).message}`);
    }
  }
}

async function importSourceFile(file: string, bust = false): Promise<Source> {
  const href = pathToFileURL(file).href + (bust ? `?t=${Date.now()}` : '');
  const mod = (await import(href)) as { default?: Source };
  const source = mod.default;
  if (!source?.id || typeof source.discover !== 'function') {
    throw new Error(`${file} does not default-export a Source`);
  }
  return source;
}

function slugFor(url: string): string {
  return new URL(url).hostname
    .replace(/^www\./, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

function renderSourceFile(id: string, a: SourceAnalysis): string {
  const header =
    `// Generated by the source analyzer from ${a.url}\n` +
    `// ${new Date().toISOString()} — do not edit by hand; re-add the URL from the dashboard to regenerate.\n` +
    `// Why ${a.kind}: ${a.reason.replace(/\n/g, ' ')}\n`;

  if (a.kind === 'api') {
    const def = { id, label: a.label, addedFrom: a.url, spec: a.api! };
    return (
      header +
      `import { defineApiSource } from '../runtime/apiSource.js';\n\n` +
      `export default defineApiSource(${JSON.stringify(def, null, 2)});\n`
    );
  }

  const def = {
    id,
    label: a.label,
    addedFrom: a.url,
    domains: a.agentic!.domains,
    hint: a.agentic!.hint,
  };
  return (
    header +
    `import { defineAgenticSource } from '../runtime/agenticSource.js';\n\n` +
    `export default defineAgenticSource(${JSON.stringify(def, null, 2)});\n`
  );
}
